version: 2.1
orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker: circleci/docker-publish@0.1.6
workflows:
  build-and-publish:
    jobs:
      - docker/publish:
          name: build-and-publish-image-dockerhub
          image: $DOCKER_LOGIN/alpine-ci
          context: general
          filters:
            branches:
              only: master
          after_build:
            - run:
                name: Tag as latest
                command: |
                  docker tag \
                    docker.io/$DOCKER_LOGIN/alpine-ci:$CIRCLE_SHA1 \
                    docker.io/$DOCKER_LOGIN/alpine-ci:latest
